### ISSUE TITLE
 tagged releases?

### ISSUE THREAD

**Issue by anarcat** [distatus/battery#9]
hi,

first, thank you for this software, it looks quite useful and is used in a tool I am packaging for debian (gotop).

one problem with this dependency is that it doesn't have official releases. it makes it hard to find out when changes happen in the code base. it also makes tracking module dependencies with the new golang module system harder.

would you consider using official, tagged releases for your software?

again thank you for your time.

**Comment by KenjiTakahashi** [comment]
Hello,

Yes, I do plan to make an official release, but wanted to do so after going through the existing issues. Hopefully I'll be able to do this in the coming days, as I'm close to over with real time stuff that was taking most of my spare time lately.
Otherwise, I may push a `0.9` or sth to the current master and do the updates later.
Either way, there should soon be a release here.

BTW: Nice to know that `gotop` uses this library, TIL :-)!

**Comment by anarcat** [comment]
> Yes, I do plan to make an official release, but wanted to do so after going through the existing issues. > Hopefully I'll be able to do this in the coming days, as I'm close to over with real time stuff that was taking most of my spare time lately.
> Otherwise, I may push a `0.9` or sth to the current master and do the updates later.
> Either way, there should soon be a release here.

Great! Thanks for considering this. And you know what "they" say, release early, release often! :) A 0.1 is better than nothing at all, in my opinion...

**Comment by KenjiTakahashi** [comment]
Alright, decided to not hold this up and pushed a `v0.9.0` tag. Will get through the issues later and make a separate release after that.
